/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spy.user;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author root
 */
public class Monitor extends javax.swing.JPanel {
    String[] info;
    /**
     * Creates new form Process
     */
    public Monitor(String[] info) {
        this.info=info;
        initComponents();
    }
    
    public String getID() {
        return info[2];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        String[] columnNames = {"Key", "Value"};
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(823, 472));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(120, 181, 241));
        jPanel1.setPreferredSize(new java.awt.Dimension(823, 472));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 94, 109));
        jLabel1.setText("Client Session Details");

        DefaultTableModel model=new javax.swing.table.DefaultTableModel();
        model.setColumnIdentifiers(columnNames);
        jTable1.setModel(model);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        //studdbid.setText(String.valueOf(info[3]));
        String name=info[0];
        model.addRow(new Object[]{"Name",name});
        String pcno=info[1];
        model.addRow(new Object[]{"PC Number",pcno});
        String studid=info[2];
        model.addRow(new Object[]{"EMP Id",studid});
        String branch=info[3];
        model.addRow(new Object[]{"Department",branch});
        String login_datetime=info[4];
        model.addRow(new Object[]{"Login datetime",login_datetime});
        String logout_datetime="";
        model.addRow(new Object[]{"Logout Datetime",logout_datetime});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jLabel1)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
